spring:
  flyway:
    enabled: false
    table: schema_version
  datasource:
    url: jdbc:h2:mem:h2db
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

  h2:
    console:
      enabled: false

logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
server:
  port: 8088